#!/usr/bin/env bash
# End-to-end test of `--live` against a local kind cluster.
#
#   e2e/kind.sh up     create the cluster, Secrets, RBAC and e2e/out/inventory.yaml
#   e2e/kind.sh run    run the scenarios, print EXPECTED vs actual, save e2e/out/run.log
#   e2e/kind.sh down   delete the cluster and e2e/out/
#
# Requirements: docker (or podman), kind, kubectl, python3 with `pip install -r requirements.txt`.
# Everything uses its own kubeconfig (e2e/out/kubeconfig): ~/.kube/config is never touched.
set -euo pipefail

CLUSTER_NAME="cert-validator-e2e"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/e2e/out"
KCFG="$OUT/kubeconfig"
ADMIN_CTX="kind-$CLUSTER_NAME"
LIMITED_CTX="$CLUSTER_NAME-limited"
PY="${PYTHON:-python3}"

kc() { kubectl --kubeconfig "$KCFG" --context "$ADMIN_CTX" "$@"; }

require() {
    local missing=0
    for bin in kind kubectl "$PY"; do
        command -v "$bin" >/dev/null || { echo "missing: $bin" >&2; missing=1; }
    done
    "$PY" -c "import cryptography, yaml, kubernetes, jks" 2>/dev/null \
        || { echo "missing Python deps: pip install -r $REPO_ROOT/requirements.txt" >&2; missing=1; }
    [ "$missing" -eq 0 ] || exit 1
}

up() {
    require
    mkdir -p "$OUT"
    if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
        kind create cluster --name "$CLUSTER_NAME" --kubeconfig "$KCFG" --wait 120s
    else
        kind get kubeconfig --name "$CLUSTER_NAME" > "$KCFG"
    fi

    "$PY" "$REPO_ROOT/e2e/make_fixtures.py" "$OUT/certs"
    local c="$OUT/certs"

    for ns in web-prod api-prod billing-prod restricted cert-validator; do
        kc create namespace "$ns" --dry-run=client -o yaml | kc apply -f - >/dev/null
    done

    # apply = idempotent re-runs of `up`
    apply_secret() { kc create secret "$@" --dry-run=client -o yaml | kc apply -f - >/dev/null; }

    # web-prod: standard kubernetes.io/tls, plus an expired cert and a cert that does not match the inventory
    apply_secret tls web-tls -n web-prod --cert "$c/web.crt" --key "$c/web.key"
    apply_secret generic old-tls -n web-prod --from-file=tls.crt="$c/legacy.crt"
    apply_secret generic mismatch-tls -n web-prod --from-file=tls.crt="$c/mismatch.crt"

    # api-prod: JKS keystore + truststore; keystore password in a separate Secret,
    # written with a trailing newline like `echo changeit | ...` would do
    printf 'changeit\n' > "$c/keystore-password"
    printf 'trustpass' > "$c/truststore-password"
    apply_secret generic api-tls -n api-prod \
        --from-file=keystore.jks="$c/api-keystore.jks" \
        --from-file=truststore.jks="$c/api-truststore.jks" \
        --from-file=truststorePassword="$c/truststore-password"
    apply_secret generic api-pass -n api-prod --from-file=keystorePassword="$c/keystore-password"

    # billing-prod: PKCS12 expiring in 10 days
    printf 'p12pass' > "$c/p12-password"
    apply_secret generic billing-tls -n billing-prod --from-file=keystore.p12="$c/billing.p12"
    apply_secret generic billing-tls-pass -n billing-prod --from-file=keystorePassword="$c/p12-password"

    # restricted: readable by the admin context only
    apply_secret tls restricted-tls -n restricted --cert "$c/web.crt" --key "$c/web.key"

    # Limited identity: ServiceAccount allowed to `get` secrets in web-prod only
    kc apply -f - >/dev/null <<EOF
apiVersion: v1
kind: ServiceAccount
metadata: {name: cert-reader, namespace: cert-validator}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: cert-reader, namespace: web-prod}
rules: [{apiGroups: [""], resources: ["secrets"], verbs: ["get"]}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: cert-reader, namespace: web-prod}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: cert-reader}
subjects: [{kind: ServiceAccount, name: cert-reader, namespace: cert-validator}]
EOF
    local token
    token="$(kc create token cert-reader -n cert-validator --duration=24h)"
    kubectl --kubeconfig "$KCFG" config set-credentials cert-reader --token="$token" >/dev/null
    kubectl --kubeconfig "$KCFG" config set-context "$LIMITED_CTX" \
        --cluster "$ADMIN_CTX" --user cert-reader >/dev/null

    cat > "$OUT/inventory.yaml" <<EOF
# Generated by e2e/kind.sh up. Expected result per asset is in the comment.
clusters:
  - name: kind-admin
    context: $ADMIN_CTX
  - name: kind-limited
    context: $LIMITED_CTX
  - name: ghost
    context: context-that-does-not-exist

assets:
  - id: web                 # OK (kubernetes.io/tls, PEM chain, EC key)
    cluster: kind-admin
    namespace: web-prod
    cn: www.example.com
    certType: pem
    keystore: {secret: {name: web-tls, key: tls.crt}}

  - id: api                 # OK (JKS + truststore, password with trailing newline, mtls)
    cluster: kind-admin
    namespace: api-prod
    cn: api.example.com
    certType: keystore
    mtls: true
    keystore:
      secret: {name: api-tls, key: keystore.jks}
      passwordRef: {name: api-pass, key: keystorePassword}
    truststore:
      secret: {name: api-tls, key: truststore.jks}
      passwordRef: {name: api-tls, key: truststorePassword}

  - id: billing             # WARNING: expires in 10 days
    cluster: kind-admin
    namespace: billing-prod
    cn: billing.internal.example.com
    certType: pkcs12
    keystore:
      secret: {name: billing-tls, key: keystore.p12}
      passwordRef: {name: billing-tls-pass, key: keystorePassword}

  - id: legacy              # WARNING: expired 5 days ago
    cluster: kind-admin
    namespace: web-prod
    cn: old.example.com
    certType: pem
    keystore: {secret: {name: old-tls, key: tls.crt}}

  - id: mismatch            # WARNING x2: certType der vs PEM, cn vs real CN
    cluster: kind-admin
    namespace: web-prod
    cn: www2.example.com
    certType: der
    keystore: {secret: {name: mismatch-tls, key: tls.crt}}

  - id: missing             # ERROR: Secret not found
    cluster: kind-admin
    namespace: web-prod
    cn: missing.example.com
    certType: pem
    keystore: {secret: {name: does-not-exist, key: tls.crt}}

  - id: web-limited         # OK through the limited ServiceAccount
    cluster: kind-limited
    namespace: web-prod
    cn: www.example.com
    certType: pem
    keystore: {secret: {name: web-tls, key: tls.crt}}

  - id: restricted          # ERROR: permission denied (RBAC)
    cluster: kind-limited
    namespace: restricted
    cn: www.example.com
    certType: pem
    keystore: {secret: {name: restricted-tls, key: tls.crt}}

  - id: ghost               # ERROR: kubeconfig context does not exist
    cluster: ghost
    namespace: web-prod
    cn: www.example.com
    certType: pem
    keystore: {secret: {name: web-tls, key: tls.crt}}
EOF

    echo
    echo "Ready. Inventory: $OUT/inventory.yaml"
    echo "Next: e2e/kind.sh run"
}

# scenario EXPECTED_RC "description" cmd...: runs one command, prints output and verdict
PASS=0
FAIL=0
scenario() {
    local expected_rc="$1" description="$2"
    shift 2
    echo
    echo "=================================================================="
    echo "SCENARIO: $description"
    echo "COMMAND:  $*"
    echo "EXPECTED: exit $expected_rc"
    echo "------------------------------------------------------------------"
    set +e
    (cd "$OUT" && "$@")
    local rc=$?
    set -e
    if [ "$rc" -eq "$expected_rc" ]; then
        echo "RESULT:   exit $rc  [OK]"
        PASS=$((PASS + 1))
    else
        echo "RESULT:   exit $rc  [UNEXPECTED, wanted $expected_rc]"
        FAIL=$((FAIL + 1))
    fi
}

run() {
    require
    [ -f "$OUT/inventory.yaml" ] || { echo "run 'e2e/kind.sh up' first" >&2; exit 1; }
    local main=("$PY" "$REPO_ROOT/main.py")
    local inv="$OUT/inventory.yaml"
    local live=(--live --kubeconfig "$KCFG")

    {
        echo "cert-asset-validator e2e run - $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "git: $(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo n/a)"
        echo "kind: $(kind version 2>/dev/null)  kubectl: $(kubectl version --client 2>/dev/null | head -1)"

        scenario 1 "validate --live: 3 OK, 3 warnings, 3 errors (see inventory comments)" \
            "${main[@]}" validate "$inv" "${live[@]}"
        scenario 1 "validate --live as table" \
            "${main[@]}" validate "$inv" "${live[@]}" --format table
        scenario 0 "search --live, real SAN match, admin cluster only, csv" \
            "${main[@]}" search "$inv" "${live[@]}" --cluster kind-admin --namespace api-prod --cn "DNS:api" --format csv
        scenario 0 "search --live billing: warning only, exit 0 without --fail-on-expiry" \
            "${main[@]}" search "$inv" "${live[@]}" --namespace billing-prod
        scenario 1 "search --live billing --fail-on-expiry (10 days < 30)" \
            "${main[@]}" search "$inv" "${live[@]}" --namespace billing-prod --fail-on-expiry
        scenario 0 "search --live billing --fail-on-expiry --warn-days 5" \
            "${main[@]}" search "$inv" "${live[@]}" --namespace billing-prod --fail-on-expiry --warn-days 5
        scenario 0 "search --live with --context override (every asset via the admin context)" \
            "${main[@]}" search "$inv" "${live[@]}" --context "$ADMIN_CTX" --namespace restricted
        scenario 0 "csr --live from JKS (password from Secret), new CN and extra SAN" \
            "${main[@]}" csr "$inv" --id api "${live[@]}" --cn api-v2.example.com --add-san DNS:api.example.com
        scenario 0 "csr --live from kubernetes.io/tls, reusing tls.key" \
            "${main[@]}" csr "$inv" --id web "${live[@]}" --reuse-key
        scenario 0 "csr --live from PKCS12, reusing the key inside the keystore" \
            "${main[@]}" csr "$inv" --id billing "${live[@]}" --reuse-key
        scenario 1 "csr --live on an asset the limited identity cannot read" \
            "${main[@]}" csr "$inv" --id restricted "${live[@]}"
        scenario 0 "analyse the generated CSR inputs: JKS keystore from disk" \
            "${main[@]}" analyse "$OUT/certs/api-keystore.jks" --password changeit --format table

        if command -v openssl >/dev/null; then
            for f in api.csr web.csr billing.csr; do
                echo
                echo "--- openssl req -in $f -noout -subject -verify"
                (cd "$OUT" && openssl req -in "$f" -noout -subject -verify 2>&1 || true)
                (cd "$OUT" && openssl req -in "$f" -noout -text 2>/dev/null | grep -A1 "Alternative Name" || true)
            done
        fi

        echo
        echo "=================================================================="
        echo "SUMMARY: $PASS scenario(s) as expected, $FAIL unexpected"
    } 2>&1 | tee "$OUT/run.log"
    echo
    echo "Log saved to $OUT/run.log"
}

down() {
    kind delete cluster --name "$CLUSTER_NAME" 2>/dev/null || true
    rm -rf "$OUT"
    echo "cluster $CLUSTER_NAME and $OUT removed"
}

case "${1:-}" in
    up) up ;;
    run) run ;;
    down) down ;;
    *) echo "usage: $0 up|run|down" >&2; exit 2 ;;
esac
